'use strict';

exports.OK = 'OK';

exports.INTERNAL_ERROR = 'INTERNAL_ERROR';
exports.MISSING_ARGUMENT = 'MISSING_ARGUMENT';
exports.INVALID_ARGUMENT_TYPE = 'INVALID_ARGUMENT_TYPE';

exports.USER_NOT_FOUND = 'USER_NOT_FOUND';
exports.DISTRICT_NOT_FOUND = 'DISTRICT_NOT_FOUND';
exports.CITY_NOT_FOUND = 'CITY_NOT_FOUND';
exports.ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND';
exports.PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
exports.COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND';
exports.REPORT_NOT_FOUND = 'REPORT_NOT_FOUND';

exports.USER_EXISTS = 'USER_EXISTS';
exports.WRONG_PASSWORD = 'WRONG_PASSWORD';
exports.IS_NOT_AUTHENTICATED = 'IS_NOT_AUTHENTICATED';